import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
public class Products {
    private JPanel panel1;
    private JLabel Webiste;
    private JCheckBox checkBox1;

    public Products() throws IOException {
        JFrame frame = new JFrame();
        Container c = frame.getContentPane();
        frame.setTitle("Products");
        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayout(1, 3));
        panel1.setBackground(Color.BLUE);
        panel1.setBounds(10, 20, 500, 400);
        JLabel label1 = new JLabel("White Tshirt");
        label1.setFont(new Font("Arial", Font.ITALIC, 18));
        label1.setForeground(Color.WHITE);
        label1.setBounds(10, 21, 10, 100);
        JLabel label2 = new JLabel("Rs 750");
        label2.setForeground(Color.WHITE);
        label2.setFont(new Font("Arial", Font.ITALIC, 18));
        label2.setBounds(80, 21, 10, 100);
        BufferedImage image = ImageIO.read(new File("C:\\Users\\Sagnik\\IdeaProjects\\GUI\\src\\alex-haigh-fEt6Wd4t4j0-unsplash.jpg"));
        JLabel label3 = new JLabel(new ImageIcon(image));
        label3.setBounds(140, 21, 50, 100);
        panel1.add(label1);
        panel1.add(label2);
        panel1.add(label3);
        c.add(panel1);
        JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayout(1, 3));
        panel2.setBounds(10, 421, 500, 400);
        panel2.setBackground(Color.CYAN);
        JLabel label4 = new JLabel("Formal Shirt");
        label4.setFont(new Font("Arial", Font.PLAIN, 18));
        JLabel label5 = new JLabel("Rs 860");
        label5.setFont(new Font("Arial", Font.PLAIN, 18));
        JLabel label6 = null;
        BufferedImage image1 = ImageIO.read(new File("C:\\Users\\Sagnik\\IdeaProjects\\GUI\\src\\benjamin-rascoe-iNvK2Xmpx8o-unsplash.jpg"));label6 = new JLabel(new ImageIcon(image1));
        panel2.add(label4);
        panel2.add(label5);
        panel2.add(label6);
        c.add(panel2);
        JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayout(1, 3));
        panel3.setBounds(511, 21, 500, 400);
        panel3.setBackground(Color.MAGENTA);
        JLabel label7 = new JLabel("Casual Shirt");
        label7.setFont(new Font("Arial", Font.PLAIN, 18));
        JLabel label8 = new JLabel("Rs 710");
        label8.setFont(new Font("Arial", Font.PLAIN, 18));
        BufferedImage image2=ImageIO.read(new File("C:\\Users\\Sagnik\\IdeaProjects\\GUI\\src\\santhosh-kumar-RqYTuWkTdEs-unsplash.jpg"));
        JLabel label9 = new JLabel(new ImageIcon((image2)));
        panel3.add(label7);
        panel3.add(label8);
        panel3.add(label9);
        c.add(panel3);
        JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayout(1, 3));
        panel4.setBounds(511, 421, 500, 400);
        panel4.setBackground(Color.YELLOW);
        c.add(panel4);
        JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayout(1, 3));
        panel5.setBounds(1013, 21, 500, 400);
        panel5.setBackground(Color.BLUE);
        c.add(panel5);
        JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayout(1, 3));
        panel6.setBounds(1013, 421, 500, 400);
        panel6.setBackground(Color.BLACK);
        c.add(panel6);
        JPanel panel7 = new JPanel();
        panel7.setBackground(Color.WHITE);
        c.add(panel7);
        //panel2.setBounds();
    }
    public static void main(String[] args) throws IOException {
        new Products();
    }
}
